version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000